server:
  port: 8080

spring:
  profiles:
    include: datasource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:sqlmap-config.xml
  type-aliases-package: com.xiong.demo.entity


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check